### PR TITLE
Extract GitHub Actions branch name from GTIHUB_REF

### LINKED ISSUE #65: The branch name is detected incorrectly for GitHub Actions
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The branch name for GitHub Actions is detected as `refs/heads/branch_name` instead of `branch_name`, e.g. `refs/heads/master` instead of `master`.

**What is the expected behavior?**

The branch name for GitHub Actions is detected correctly.

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**

This is the issue from my PR #64 

Relates SO question: https://stackoverflow.com/q/58033366/1331425

### PR DESCRIPTION
**Pull request by limonte**
**What kind of change does this PR introduce?**

Fixes #65 

**Did you add tests for your changes?**

Yes

**Summary**

GitHub only provides `GITHUB_REF` env variable which contains ref, not branch name. Here's the difference between ref and branch name: https://stackoverflow.com/q/1526471

Here's the relates SO question: https://stackoverflow.com/q/58033366

### CODE REVIEW

**Comment by limonte** [comment]
I don't know why CI is failing, the output is kinda messy :/

**Comment by limonte** [comment]
ping @jakebolam @iamogbz @tgrant59

Guys, please tell me that `bundlewatch` isn't another `bundlesize` :)

> Bundlesize has entered maintenance mode and pull requests are left hanging, so we wanted to reboot the community through creating BundleWatch

GitHub Actions support is the dealbreaker for many devs, you can lure some users from bundlesize: https://github.com/siddharthkp/bundlesize/issues/348

**Comment by limonte** [comment]
> please tell me that bundlewatch isn't another bundlesize :)

So it seems :/

**Comment by iamogbz** [comment]
@limonte I'll try and get to all these open PRs and Issues over the break. First need to solve the broken build on master

**Review by jakebolam — APPROVED** [review]

**Comment by ctavan** [comment]
@iamogbz @jakebolam @limonte is there anything I could help with to get this one merged and a new release of bundlewatch out so that we can start using it with Github actions?

**Comment by limonte** [comment]
Guys, reviewing and merging this PR will literally take max 30 min. If you can't dedicate that amount of time for this project, consider [archiving it](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository).

> When you archive a repository, you are letting people know that a project is no longer actively maintained.

> You can archive a repository to make it read-only for all users and indicate that it's no longer actively maintained. You can also unarchive repositories that have been archived.

**Comment by limonte** [comment]
Better late than never!

Thank you @iamogbz for taking care of things! I tested out the new release in https://github.com/sweetalert2/sweetalert2/pull/1915 

All is well :rocket:

**Comment by jakebolam** [comment]
@limonte @ctavan are you interested in becoming maintainers of the project?

**Comment by limonte** [comment]
nope

**Comment by ctavan** [comment]
First of all thanks for merging, tried it in https://github.com/uuidjs/uuid/pull/404 and it seems to work well!

I'm happy to supply pull requests for issues I encounter, however I currently won't find enough time to become an active maintainer of this project.

**Pull request merged**
